[package]
name = "practice"
version = "0.1.0"
authors = ["caibirdme <englanq@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mmm"
path = "src/lib.rs"

[dependencies]
